<footer>
    <a class="FC" href = "mailto:102233170@student.swin.edu.au ">Chirathi Perera</a>
    <a class="FC" href = "mailto:103533680@student.swin.edu.au ">Gia Bao</a>
    <a class="FC" href = "mailto:103947870@student.swin.edu.au">Eloise Grant</a>
    <a class="FC" href = "mailto:104017813@student.swin.edu.au">Taliah Brooker</a>
    <a class="FC" href = "mailto:103996827@student.swin.edu.au ">Jordan Virgona</a>
</footer>
</body>
</html>