<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="description" content="Computing Technology Inquiry Project - COS10026 Assignment 1"/>
        <meta name="keywords" content="HTML, CSS, PHP"/>
        <meta name="Author"   content="Chirathi and Eloise" />
        <link rel="stylesheet" href="styles/style.css">
        <title> Sweb Website</title>
    </head>
    <body>
        <h1>IPV4/IPV6: A Useful Insight for Newbies</h1>

    
